# Generated by Django 5.2.5 on 2025-08-21 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessvalue',
            name='business_value_en',
            field=models.TextField(help_text='Объяснение бизнес-ценности', null=True, verbose_name='Бизнес ценность'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='business_value_ge',
            field=models.TextField(help_text='Объяснение бизнес-ценности', null=True, verbose_name='Бизнес ценность'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='business_value_ru',
            field=models.TextField(help_text='Объяснение бизнес-ценности', null=True, verbose_name='Бизнес ценность'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='business_value_uk',
            field=models.TextField(help_text='Объяснение бизнес-ценности', null=True, verbose_name='Бизнес ценность'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='situation_en',
            field=models.TextField(help_text='Описание ситуации', null=True, verbose_name='Ситуация'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='situation_ge',
            field=models.TextField(help_text='Описание ситуации', null=True, verbose_name='Ситуация'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='situation_ru',
            field=models.TextField(help_text='Описание ситуации', null=True, verbose_name='Ситуация'),
        ),
        migrations.AddField(
            model_name='businessvalue',
            name='situation_uk',
            field=models.TextField(help_text='Описание ситуации', null=True, verbose_name='Ситуация'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='content_ge',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='title_ge',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coffeeinfo',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание инструкции'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='content_ge',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание инструкции'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание инструкции'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание инструкции'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='title_ge',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='jobinstruction',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ge',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ge',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='content_ge',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_ge',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
